# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWin.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 650)
        MainWindow.setMinimumSize(QtCore.QSize(800, 650))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 788, 612))
        self.layoutWidget.setObjectName("layoutWidget")
        self.showGrid = QtWidgets.QGridLayout(self.layoutWidget)
        self.showGrid.setContentsMargins(0, 0, 0, 0)
        self.showGrid.setObjectName("showGrid")
        self.showBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.showBox.setMinimumSize(QtCore.QSize(620, 510))
        self.showBox.setObjectName("showBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.showBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.refreshSelfBtn = QtWidgets.QPushButton(self.showBox)
        self.refreshSelfBtn.setObjectName("refreshSelfBtn")
        self.gridLayout_4.addWidget(self.refreshSelfBtn, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(35, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 1, 1, 1)
        self.prevPageBtn = QtWidgets.QPushButton(self.showBox)
        self.prevPageBtn.setObjectName("prevPageBtn")
        self.gridLayout_4.addWidget(self.prevPageBtn, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(35, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 3, 1, 1)
        self.curPageNoEdit = QtWidgets.QLineEdit(self.showBox)
        self.curPageNoEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.curPageNoEdit.setObjectName("curPageNoEdit")
        self.gridLayout_4.addWidget(self.curPageNoEdit, 0, 4, 1, 1)
        self.totalPageLable = QtWidgets.QLabel(self.showBox)
        self.totalPageLable.setObjectName("totalPageLable")
        self.gridLayout_4.addWidget(self.totalPageLable, 0, 5, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(36, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 0, 6, 1, 1)
        self.nextPageBtn = QtWidgets.QPushButton(self.showBox)
        self.nextPageBtn.setObjectName("nextPageBtn")
        self.gridLayout_4.addWidget(self.nextPageBtn, 0, 7, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(35, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 0, 8, 1, 1)
        self.refreshBtn = QtWidgets.QPushButton(self.showBox)
        self.refreshBtn.setObjectName("refreshBtn")
        self.gridLayout_4.addWidget(self.refreshBtn, 0, 9, 1, 1)
        self.showTable = QtWidgets.QTableView(self.showBox)
        self.showTable.setMinimumSize(QtCore.QSize(600, 480))
        self.showTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.showTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.showTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.showTable.setObjectName("showTable")
        self.gridLayout_4.addWidget(self.showTable, 1, 0, 1, 10)
        self.showGrid.addWidget(self.showBox, 1, 1, 1, 1)
        self.accountBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.accountBox.setMinimumSize(QtCore.QSize(620, 60))
        self.accountBox.setMaximumSize(QtCore.QSize(16777215, 50))
        self.accountBox.setObjectName("accountBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.accountBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 0, 0, 1, 1)
        self.textLable = QtWidgets.QLabel(self.accountBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textLable.setFont(font)
        self.textLable.setObjectName("textLable")
        self.gridLayout_3.addWidget(self.textLable, 0, 4, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 0, 6, 1, 1)
        self.loadTimeLable2 = QtWidgets.QLabel(self.accountBox)
        self.loadTimeLable2.setText("")
        self.loadTimeLable2.setObjectName("loadTimeLable2")
        self.gridLayout_3.addWidget(self.loadTimeLable2, 0, 5, 1, 1)
        self.userLable = QtWidgets.QLabel(self.accountBox)
        self.userLable.setText("")
        self.userLable.setObjectName("userLable")
        self.gridLayout_3.addWidget(self.userLable, 0, 3, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 0, 2, 1, 1)
        self.PlcConStatu = QtWidgets.QPushButton(self.accountBox)
        self.PlcConStatu.setMinimumSize(QtCore.QSize(85, 30))
        self.PlcConStatu.setText("")
        self.PlcConStatu.setObjectName("PlcConStatu")
        self.gridLayout_3.addWidget(self.PlcConStatu, 0, 1, 1, 1)
        self.ScanConStatu = QtWidgets.QPushButton(self.accountBox)
        self.ScanConStatu.setMinimumSize(QtCore.QSize(85, 30))
        self.ScanConStatu.setText("")
        self.ScanConStatu.setObjectName("ScanConStatu")
        self.gridLayout_3.addWidget(self.ScanConStatu, 0, 7, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem7, 0, 8, 1, 1)
        self.showGrid.addWidget(self.accountBox, 0, 1, 1, 1)
        self.settingBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.settingBox.setMinimumSize(QtCore.QSize(160, 610))
        self.settingBox.setObjectName("settingBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.settingBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem8, 15, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem9, 7, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.loadTimeLable = QtWidgets.QLabel(self.settingBox)
        self.loadTimeLable.setObjectName("loadTimeLable")
        self.verticalLayout_7.addWidget(self.loadTimeLable)
        self.loadTime = QtWidgets.QLineEdit(self.settingBox)
        self.loadTime.setObjectName("loadTime")
        self.verticalLayout_7.addWidget(self.loadTime)
        self.gridLayout.addLayout(self.verticalLayout_7, 16, 0, 1, 2)
        self.setBtn = QtWidgets.QPushButton(self.settingBox)
        self.setBtn.setObjectName("setBtn")
        self.gridLayout.addWidget(self.setBtn, 1, 0, 2, 2)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem10, 13, 0, 1, 1)
        self.changePwdBtn = QtWidgets.QPushButton(self.settingBox)
        self.changePwdBtn.setObjectName("changePwdBtn")
        self.gridLayout.addWidget(self.changePwdBtn, 18, 0, 1, 2)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem11, 9, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem12, 17, 0, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.classLable = QtWidgets.QLabel(self.settingBox)
        self.classLable.setObjectName("classLable")
        self.verticalLayout_6.addWidget(self.classLable)
        self.classBox = QtWidgets.QComboBox(self.settingBox)
        self.classBox.setObjectName("classBox")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.classBox.addItem("")
        self.verticalLayout_6.addWidget(self.classBox)
        self.gridLayout.addLayout(self.verticalLayout_6, 14, 0, 1, 2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.typeLable = QtWidgets.QLabel(self.settingBox)
        self.typeLable.setObjectName("typeLable")
        self.verticalLayout_5.addWidget(self.typeLable)
        self.type = QtWidgets.QLineEdit(self.settingBox)
        self.type.setObjectName("type")
        self.verticalLayout_5.addWidget(self.type)
        self.gridLayout.addLayout(self.verticalLayout_5, 12, 0, 1, 2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.processNoLable = QtWidgets.QLabel(self.settingBox)
        self.processNoLable.setObjectName("processNoLable")
        self.verticalLayout_3.addWidget(self.processNoLable)
        self.processNo = QtWidgets.QLineEdit(self.settingBox)
        self.processNo.setObjectName("processNo")
        self.verticalLayout_3.addWidget(self.processNo)
        self.gridLayout.addLayout(self.verticalLayout_3, 8, 0, 1, 2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.machinIDLable = QtWidgets.QLabel(self.settingBox)
        self.machinIDLable.setObjectName("machinIDLable")
        self.verticalLayout.addWidget(self.machinIDLable)
        self.machineID = QtWidgets.QLineEdit(self.settingBox)
        self.machineID.setObjectName("machineID")
        self.verticalLayout.addWidget(self.machineID)
        self.gridLayout.addLayout(self.verticalLayout, 4, 0, 1, 2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.localityLable = QtWidgets.QLabel(self.settingBox)
        self.localityLable.setObjectName("localityLable")
        self.verticalLayout_4.addWidget(self.localityLable)
        self.localityNo = QtWidgets.QLineEdit(self.settingBox)
        self.localityNo.setObjectName("localityNo")
        self.verticalLayout_4.addWidget(self.localityNo)
        self.gridLayout.addLayout(self.verticalLayout_4, 10, 0, 1, 2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plantIDLable = QtWidgets.QLabel(self.settingBox)
        self.plantIDLable.setObjectName("plantIDLable")
        self.verticalLayout_2.addWidget(self.plantIDLable)
        self.plantID = QtWidgets.QLineEdit(self.settingBox)
        self.plantID.setObjectName("plantID")
        self.verticalLayout_2.addWidget(self.plantID)
        self.gridLayout.addLayout(self.verticalLayout_2, 6, 0, 1, 2)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem13, 5, 0, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem14, 3, 0, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem15, 11, 0, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem16, 0, 0, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem17, 19, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.showGrid.addWidget(self.settingBox, 0, 0, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.setBtn, self.machineID)
        MainWindow.setTabOrder(self.machineID, self.plantID)
        MainWindow.setTabOrder(self.plantID, self.processNo)
        MainWindow.setTabOrder(self.processNo, self.localityNo)
        MainWindow.setTabOrder(self.localityNo, self.type)
        MainWindow.setTabOrder(self.type, self.classBox)
        MainWindow.setTabOrder(self.classBox, self.loadTime)
        MainWindow.setTabOrder(self.loadTime, self.changePwdBtn)
        MainWindow.setTabOrder(self.changePwdBtn, self.refreshSelfBtn)
        MainWindow.setTabOrder(self.refreshSelfBtn, self.refreshBtn)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "包装机监控"))
        self.showBox.setTitle(_translate("MainWindow", "显示"))
        self.refreshSelfBtn.setText(_translate("MainWindow", "自动刷新"))
        self.prevPageBtn.setText(_translate("MainWindow", "上一页"))
        self.totalPageLable.setText(_translate("MainWindow", "/ (共 页)"))
        self.nextPageBtn.setText(_translate("MainWindow", "下一页"))
        self.refreshBtn.setText(_translate("MainWindow", "手动刷新"))
        self.accountBox.setTitle(_translate("MainWindow", "账号信息"))
        self.textLable.setText(_translate("MainWindow", "欢迎您！ 您的本次登陆时间是："))
        self.settingBox.setTitle(_translate("MainWindow", "设置"))
        self.loadTimeLable.setText(_translate("MainWindow", "登录时间"))
        self.setBtn.setText(_translate("MainWindow", "编   辑"))
        self.changePwdBtn.setText(_translate("MainWindow", "修改密码"))
        self.classLable.setText(_translate("MainWindow", "班次"))
        self.classBox.setItemText(0, _translate("MainWindow", "甲班"))
        self.classBox.setItemText(1, _translate("MainWindow", "乙班"))
        self.classBox.setItemText(2, _translate("MainWindow", "丙班"))
        self.typeLable.setText(_translate("MainWindow", "采集点类型"))
        self.processNoLable.setText(_translate("MainWindow", "工序编号"))
        self.machinIDLable.setText(_translate("MainWindow", "设备编号"))
        self.localityLable.setText(_translate("MainWindow", "采集点编码"))
        self.plantIDLable.setText(_translate("MainWindow", "工厂编码"))

